/* errno.h - WindowsCE errno.h substitute
   Copyright (C) 2010 g10 Code GmbH

   This file is free software; as a special exception the author gives
   unlimited permission to copy and/or distribute it, with or without
   modifications, as long as this notice is preserved.

   This file is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY, to the extent permitted by law; without even
   the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
   PURPOSE.

   +++ Do not edit!  File has been generated by mkw32errmap.c +++

   This file is intended to be used with ming32ce-gcc to implement an
   errno substitute under WindowsCE.  It must be included via gcc's
   -idirafter option.  The gpg-error-config script emits the
   appropriate option snippet.  The actual implementation of the errno
   related functions are part of libgpg-error.  A separate header file
   is required because errno.h is often included before gpg-error.h.
 */

#ifndef _GPG_ERROR_EXTRA_ERRNO_H
#define _GPG_ERROR_EXTRA_ERRNO_H

/* Due to peculiarities in W32 we can't implement ERRNO as an
   writable lvalue.  This also allows us to easily find places
   where ERRNO is being written to.  See also gpg_err_set_errno.  */
int _gpg_w32ce_get_errno (void);
#define errno (_gpg_w32ce_get_errno ())

#define ENOENT           2
#define EMFILE           4
#define EACCES           5
#define EBADF            6
#define ENOMEM           8
#define EXDEV           17
#define ENFILE          18
#define EROFS           19
#define ENOLCK          36
#define ENOSYS          50
#define EEXIST          80
#define EPERM           82
#define EINVAL          87
#define EINTR          104
#define EPIPE          109
#define ENOSPC         112
#define ENOTEMPTY      145
#define EBUSY          170
#define ENAMETOOLONG   206
#define EAGAIN         234
#define ENOTDIR        267
#define ERANGE         534
#define ENXIO         1006
#define EFAULT        1067
#define EIO           1117
#define EDEADLOCK     1131
#define ENODEV        1200

#endif /*_GPG_ERROR_EXTRA_ERRNO_H*/
